## PostgreSQL
spring.datasource.url=jdbc:postgresql://ec2-54-228-139-34.eu-west-1.compute.amazonaws.com/d948readqkqbrg
spring.datasource.username=rxjomdeirqjrxq
spring.datasource.password=730df95f13a7b7071725621234642e6b5530bb6e32b275298e98e93c3e607890
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.port=8686
server.error.whitelabel.enabled=false


#spring.datasource.url=jdbc:postgresql://localhost:5432/operatorsJSON_DB
#spring.datasource.username=postgres
#spring.datasource.password=P@ssw0rd01
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#server.port=8686
#server.error.whitelabel.enabled=false