## PostgreSQL

#Beta-test
spring.datasource.url=jdbc:postgresql://dsgmtbrzsxojif:e8456da8150cec2a9dd8e977f8c29200925ee209f2c79bb2fe1b17b539a34547@ec2-52-19-164-214.eu-west-1.compute.amazonaws.com:5432/d1echisucschrd
spring.datasource.username=dsgmtbrzsxojif
spring.datasource.password=e8456da8150cec2a9dd8e977f8c29200925ee209f2c79bb2fe1b17b539a34547
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.port=8686
server.error.whitelabel.enabled=false


#Production
#spring.datasource.url=jdbc:postgresql://ec2-34-250-16-127.eu-west-1.compute.amazonaws.com/deop6rg7319ab8
#spring.datasource.username=fnvpdlrtswigev
#spring.datasource.password=b38f3a851823f5766969733ef743630d93f2d6fccd1e054039f25e6048614ca5
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#server.port=8686
#server.error.whitelabel.enabled=false

#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/operatorsJSON_DB
#spring.datasource.username=postgres
#spring.datasource.password=P@ssw0rd01
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#server.port=8686
#server.error.whitelabel.enabled=false