## PostgreSQL

spring.datasource.url=jdbc:postgresql://ec2-34-250-16-127.eu-west-1.compute.amazonaws.com/deop6rg7319ab8
spring.datasource.username=bnrcdhkjpuiwmd
spring.datasource.password=e6282bcff069c1087b9e13b00a850e69d5802e546f1962cdb0da11432380598b
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
server.port=8686
server.error.whitelabel.enabled=false

#spring.datasource.url=jdbc:postgresql://localhost:5432/operatorsJSON_DB
#spring.datasource.username=postgres
#spring.datasource.password=P@ssw0rd01
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#server.port=8686
#server.error.whitelabel.enabled=false